/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p23;

import javax.swing.JOptionPane;

/**
 *
 * @author 18progb0404
 */
public class FrmInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicio
     */
    public FrmInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblcuadrado = new javax.swing.JLabel();
        lblcirculo = new javax.swing.JLabel();
        lbltriangulo = new javax.swing.JLabel();
        lblrombo = new javax.swing.JLabel();
        lbllado = new javax.swing.JLabel();
        lblareaC = new javax.swing.JLabel();
        txtlado = new javax.swing.JTextField();
        btncalcularC = new javax.swing.JButton();
        txtbaseT = new javax.swing.JTextField();
        lblbaseT = new javax.swing.JLabel();
        lblaltura = new javax.swing.JLabel();
        txtalturaT = new javax.swing.JTextField();
        lblareaT = new javax.swing.JLabel();
        btncalcularT = new javax.swing.JButton();
        lblradio = new javax.swing.JLabel();
        lblareaCi = new javax.swing.JLabel();
        txtradio = new javax.swing.JTextField();
        btncalcularCi = new javax.swing.JButton();
        lbldiagonalma = new javax.swing.JLabel();
        lbldiagonalme = new javax.swing.JLabel();
        lblareaRo = new javax.swing.JLabel();
        txtdiagonalma = new javax.swing.JTextField();
        txtdiagonalme = new javax.swing.JTextField();
        btncalcularRo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("AREA DE FIGURAS GEOMETRICAS  ");

        lblcuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadrado.png"))); // NOI18N
        lblcuadrado.setText("jLabel2");

        lblcirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circulo.png"))); // NOI18N
        lblcirculo.setText("jLabel3");

        lbltriangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/triangulo.png"))); // NOI18N
        lbltriangulo.setText("jLabel4");

        lblrombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rombo.jpg"))); // NOI18N
        lblrombo.setText("jLabel5");

        lbllado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbllado.setText("lado");

        lblareaC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblareaC.setText("area");

        txtlado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtlado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtladoActionPerformed(evt);
            }
        });

        btncalcularC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncalcularC.setText("calcular");
        btncalcularC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularCActionPerformed(evt);
            }
        });

        txtbaseT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtbaseT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbaseTActionPerformed(evt);
            }
        });

        lblbaseT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblbaseT.setText("base");

        lblaltura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblaltura.setText("altura");

        txtalturaT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblareaT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblareaT.setText("area");

        btncalcularT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncalcularT.setText("calcular");
        btncalcularT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularTActionPerformed(evt);
            }
        });

        lblradio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblradio.setText("radio");

        lblareaCi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblareaCi.setText("area");

        txtradio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btncalcularCi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncalcularCi.setText("calcular");
        btncalcularCi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularCiActionPerformed(evt);
            }
        });

        lbldiagonalma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbldiagonalma.setText("diagonal mayor");

        lbldiagonalme.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbldiagonalme.setText("diagonal menor");

        lblareaRo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblareaRo.setText("area");

        txtdiagonalma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtdiagonalme.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btncalcularRo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncalcularRo.setText("calcular");
        btncalcularRo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularRoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblcuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbltriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblareaT)
                        .addGap(205, 205, 205))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lbllado)
                        .addGap(147, 147, 147)
                        .addComponent(lblareaC)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblbaseT)
                                        .addGap(68, 68, 68)
                                        .addComponent(lblaltura))
                                    .addComponent(txtlado, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblradio)
                                            .addComponent(txtbaseT, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addComponent(txtalturaT, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(155, 155, 155)
                                                .addComponent(lblareaCi))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(212, 212, 212)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btncalcularC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btncalcularT, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btncalcularCi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblrombo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdiagonalma, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldiagonalma))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbldiagonalme, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdiagonalme, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btncalcularRo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblareaRo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblcirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtradio, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbllado)
                            .addComponent(lblareaC)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtlado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcuadrado)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btncalcularC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lbltriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblbaseT)
                            .addComponent(lblaltura)
                            .addComponent(lblareaT))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbaseT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtalturaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncalcularT))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblcirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtradio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblradio)
                            .addComponent(lblareaCi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncalcularCi)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblrombo, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldiagonalma, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldiagonalme, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblareaRo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdiagonalma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdiagonalme, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncalcularRo))
                        .addGap(88, 88, 88))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbaseTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbaseTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbaseTActionPerformed

    private void btncalcularCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularCActionPerformed
        try {
            Double lado = Double.parseDouble(txtlado.getText());
            lblareaC.setText(String.valueOf(Math.pow(lado, 2)));
            txtlado.setText("");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "error, debes ingresar un valor");
            System.out.println(ex.toString());

        }

    }//GEN-LAST:event_btncalcularCActionPerformed

    private void txtladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtladoActionPerformed

    private void btncalcularTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularTActionPerformed
        try{
            double base = Double.parseDouble(txtbaseT.getText());
            double altura = Double.parseDouble(txtalturaT.getText());
            lblareaT.setText(String.valueOf(base * altura / 2)) ;
            txtbaseT.setText("");
            txtalturaT.setText("");
         } catch (NumberFormatException ex) {
             lblareaT.setText("0");
             System.out.println(ex.toString());
         }
        
        
    }//GEN-LAST:event_btncalcularTActionPerformed

    private void btncalcularCiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularCiActionPerformed
        try{
        double radio = Double.parseDouble(txtradio.getText());
          lblareaCi.setText(String.valueOf(3.1416 *Math.pow(radio,2) )) ;
            txtradio.setText("");
        }catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Error debes ingresar un valor:");
            System.out.println(ex.toString());
        }
        
    }//GEN-LAST:event_btncalcularCiActionPerformed

    private void btncalcularRoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularRoActionPerformed
        try{
        double diagonalma = Double.parseDouble(txtdiagonalma.getText());
        double diagonalme = Double.parseDouble(txtdiagonalme.getText());
        lblareaRo.setText(String.valueOf(diagonalma *diagonalme /2 )) ;
        txtdiagonalma.setText("");
        txtdiagonalme.setText("");
        
         } catch (NumberFormatException ex){
    JOptionPane.showMessageDialog(null, "Error debes ingresar un valor:");
            System.out.println(ex.toString());
          }
            
    }//GEN-LAST:event_btncalcularRoActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcularC;
    private javax.swing.JButton btncalcularCi;
    private javax.swing.JButton btncalcularRo;
    private javax.swing.JButton btncalcularT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblaltura;
    private javax.swing.JLabel lblareaC;
    private javax.swing.JLabel lblareaCi;
    private javax.swing.JLabel lblareaRo;
    private javax.swing.JLabel lblareaT;
    private javax.swing.JLabel lblbaseT;
    private javax.swing.JLabel lblcirculo;
    private javax.swing.JLabel lblcuadrado;
    private javax.swing.JLabel lbldiagonalma;
    private javax.swing.JLabel lbldiagonalme;
    private javax.swing.JLabel lbllado;
    private javax.swing.JLabel lblradio;
    private javax.swing.JLabel lblrombo;
    private javax.swing.JLabel lbltriangulo;
    private javax.swing.JTextField txtalturaT;
    private javax.swing.JTextField txtbaseT;
    private javax.swing.JTextField txtdiagonalma;
    private javax.swing.JTextField txtdiagonalme;
    private javax.swing.JTextField txtlado;
    private javax.swing.JTextField txtradio;
    // End of variables declaration//GEN-END:variables
}
